[phases.setup]
nixPkgs = ["nodejs"]

[phases.build]
cmds = [
  "npm install",
  "npx puppeteer browsers install chrome"
]

[start]
cmd = "node index.js"

[variables]
PUPPETEER_EXECUTABLE_PATH = "/app/.cache/puppeteer/chrome/linux-*/chrome-linux/chrome"
